# Generated by Django 3.0.7 on 2023-01-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=100, null=True)),
                ('surnName', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('local_goverment_area', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.CharField(max_length=100, null=True)),
                ('date_of_Resumption', models.CharField(max_length=100, null=True)),
                ('marital_status', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('religion', models.CharField(max_length=100, null=True)),
                ('olevel_number_of_sittings', models.CharField(max_length=100, null=True)),
                ('student_num', models.CharField(max_length=100)),
                ('fathers_num', models.CharField(max_length=100, null=True)),
                ('mothers_num', models.CharField(max_length=100, null=True)),
                ('sub_comb_1', models.CharField(max_length=100, null=True)),
                ('sub_comb_2', models.CharField(max_length=100, null=True)),
                ('sub_comb_3', models.CharField(max_length=100, null=True)),
                ('first_choice', models.CharField(max_length=100, null=True)),
                ('first_choice_course', models.CharField(max_length=100, null=True)),
                ('second_choice', models.CharField(max_length=100, null=True)),
                ('second_choice_course', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('father_occupation', models.CharField(max_length=100, null=True)),
                ('mother_occupation', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
